Task/02 interfaces
vBrusentsov/fe-react-2024 pull request #2
Opened 2024-04-25 05:08 UTC by vBrusentsov

2024-04-28 18:42 UTC, MZabolotnev requested changes

2024-04-28 18:42 UTC, MZabolotnev commented on src/interface/product-interface.ts
> +    images: [string];
Should be string[]

2024-04-29 16:09 UTC, vBrusentsov commented on src/interface/product-interface.ts
> +    images: [string];
I done it

2024-04-29 17:42 UTC, MZabolotnev approved these changes

2024-04-30 04:18 UTC, merged