Task/04 styling
vBrusentsov/fe-react-2024 pull request #4
Opened 2024-05-23 10:58 UTC by vBrusentsov

- [ ] Mentor is added to PR
- [ ] AC copied to PR description
- [ ] Link to deployed version is added to PR
- [ ] Added layout of Search Bar
- [ ] Rewritten all styles with Module Styles
- [ ] Implemented dynamic theme change logic

2024-05-24 20:18 UTC, MZabolotnev reviewed
![image](https://github.com/vBrusentsov/fe-react-2024/assets/25617217/82937408-9338-4f04-ba15-da0852b00925)
Links colour is missing in dark theme

2024-05-24 20:31 UTC, MZabolotnev requested changes

2024-05-24 20:31 UTC, MZabolotnev commented on src/components/button/button.module.css
> +/*}*/
Pls remove comments

2024-05-26 11:39 UTC, vBrusentsov commented on src/components/button/button.module.css
> +/*}*/
I removed this comments

2024-05-28 21:09 UTC, MZabolotnev approved these changes

2024-05-28 21:09 UTC, merged